# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QHeaderView


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(970, 704)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")

        # ===================================================================
        # Tab 1: 认证 (Authentication) - NOW WITH SCROLLAREA
        # ===================================================================
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        # 1. Create a main layout for the tab itself
        self.tab_main_layout = QtWidgets.QVBoxLayout(self.tab)
        self.tab_main_layout.setContentsMargins(0, 0, 0, 0)

        # 2. Create the Scroll Area
        self.scrollArea_auth = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_auth.setWidgetResizable(True)  # This is crucial!
        self.scrollArea_auth.setObjectName("scrollArea_auth")

        # 3. Create the widget that will contain the content
        self.scrollAreaWidgetContents_auth = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_auth.setGeometry(QtCore.QRect(0, 0, 946, 621))
        self.scrollAreaWidgetContents_auth.setObjectName("scrollAreaWidgetContents_auth")

        # 4. Use your original layout for the content widget
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_auth)
        self.gridLayout_2.setObjectName("gridLayout_2")

        # --- Add your GroupBoxes to the content widget's layout ---
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_auth)
        # ... (rest of groupBox setup is identical)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox_proxy_platform_select = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_proxy_platform_select.setObjectName("comboBox_proxy_platform_select")
        self.verticalLayout.addWidget(self.comboBox_proxy_platform_select)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_proxy_platform_user = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_proxy_platform_user.setObjectName("lineEdit__proxy_platform_user")
        self.verticalLayout.addWidget(self.lineEdit_proxy_platform_user)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_proxy_platform_pass = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_proxy_platform_pass.setObjectName("lineEdit__proxy_platform_pass")
        self.verticalLayout.addWidget(self.lineEdit_proxy_platform_pass)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)

        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_auth)
        # ... (rest of groupBox_2 setup is identical)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit_read_email_user = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_read_email_user.setObjectName("lineEdit_read_email_user")
        self.verticalLayout_2.addWidget(self.lineEdit_read_email_user)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lineEdit_read_email_pass = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_read_email_pass.setObjectName("lineEdit_read_email_pass")
        self.verticalLayout_2.addWidget(self.lineEdit_read_email_pass)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_auth)
        # ... (rest of groupBox_3 setup is identical)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineEdit_app_auth = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_app_auth.setObjectName("lineEdit_app_auth")
        self.verticalLayout_3.addWidget(self.lineEdit_app_auth)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_auth_pass_msg = QtWidgets.QLabel(self.groupBox_3)
        self.label_auth_pass_msg.setObjectName("label_auth_pass_msg")
        self.verticalLayout_3.addWidget(self.label_auth_pass_msg)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)

        # Add a spacer to push content to the top
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)

        # 5. Set the content widget for the scroll area
        self.scrollArea_auth.setWidget(self.scrollAreaWidgetContents_auth)
        # 6. Add the scroll area to the tab's main layout
        self.tab_main_layout.addWidget(self.scrollArea_auth)

        self.tabWidget.addTab(self.tab, "")

        # ===================================================================
        # Tab 2: 代理 (Proxy) - NOW WITH SCROLLAREA
        # ===================================================================
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_2_main_layout = QtWidgets.QVBoxLayout(self.tab_2)
        self.tab_2_main_layout.setContentsMargins(0, 0, 0, 0)

        self.scrollArea_proxy = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_proxy.setWidgetResizable(True)
        self.scrollArea_proxy.setObjectName("scrollArea_proxy")

        self.scrollAreaWidgetContents_proxy = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_proxy.setGeometry(QtCore.QRect(0, 0, 946, 621))
        self.scrollAreaWidgetContents_proxy.setObjectName("scrollAreaWidgetContents_proxy")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_proxy)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        # --- Add your GroupBoxes to this layout ---
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_proxy)
        # ... (rest of groupBox_4 setup is identical)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget_link_ignore = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_link_ignore.setObjectName("listWidget_link_ignore")
        self.verticalLayout_5.addWidget(self.listWidget_link_ignore)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_link_ignore_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_link_ignore_input.setObjectName("lineEdit_link_ignore_input")
        self.horizontalLayout.addWidget(self.lineEdit_link_ignore_input)
        self.pushButton_link_ignore_add = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_link_ignore_add.setObjectName("pushButton_link_ignore_add")
        self.horizontalLayout.addWidget(self.pushButton_link_ignore_add)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.pushButton_link_ignore_del = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_link_ignore_del.setObjectName("pushButton_link_ignore_del")
        self.verticalLayout_5.addWidget(self.pushButton_link_ignore_del)
        self.verticalLayout_4.addWidget(self.groupBox_4)

        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_proxy)
        # ... (rest of groupBox_5 setup is identical)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_url_pattern = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget_url_pattern.setObjectName("tableWidget_url_pattern")
        self.tableWidget_url_pattern.setColumnCount(3)
        self.tableWidget_url_pattern.setRowCount(0)
        self.tableWidget_url_pattern.verticalHeader().setVisible(False)
        self.tableWidget_url_pattern.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_url_pattern.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_url_pattern.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_url_pattern.setHorizontalHeaderItem(2, item)

        self.verticalLayout_6.addWidget(self.tableWidget_url_pattern)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_url_pattern_add = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_url_pattern_add.setObjectName("pushButton_url_pattern_add")
        self.horizontalLayout_2.addWidget(self.pushButton_url_pattern_add)
        self.pushButton_url_pattern_del = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_url_pattern_del.setObjectName("pushButton_url_pattern_del")
        self.horizontalLayout_2.addWidget(self.pushButton_url_pattern_del)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.scrollArea_proxy.setWidget(self.scrollAreaWidgetContents_proxy)
        self.tab_2_main_layout.addWidget(self.scrollArea_proxy)
        self.tabWidget.addTab(self.tab_2, "")


        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_data_gen_is_depend = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_data_gen_is_depend.setObjectName("checkBox_data_gen_is_depend")
        self.gridLayout_3.addWidget(self.checkBox_data_gen_is_depend, 0, 0, 1, 1)
        self.checkBox_notification = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_notification.setObjectName("checkBox_notification")
        self.gridLayout_3.addWidget(self.checkBox_notification, 0, 1, 1, 1)

        self.checkBox_table_auto_copy = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_table_auto_copy.setObjectName("checkBox_table_auto_copy")
        self.gridLayout_3.addWidget(self.checkBox_table_auto_copy, 0, 2, 1, 1)

        self.checkBox_table_copy_line_wrap = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_table_copy_line_wrap.setObjectName("checkBox_table_copy_line_wrap")
        self.gridLayout_3.addWidget(self.checkBox_table_copy_line_wrap, 0, 3, 1, 1)


        self.groupBox_delimiter = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_delimiter.setObjectName("groupBox_delimiter")
        self.groupBox_delimiter.setMaximumSize(150, 200)
        self.verticalLayout_delimiter = QtWidgets.QVBoxLayout(self.groupBox_delimiter)
        self.verticalLayout_delimiter.setObjectName("verticalLayout_delimiter")
        self.listWidget_delimiter = QtWidgets.QListWidget(self.groupBox_delimiter)
        self.listWidget_delimiter.setObjectName("listWidget_delimiter")
        self.verticalLayout_delimiter.addWidget(self.listWidget_delimiter)
        self.horizontalLayout_delimiter_input = QtWidgets.QHBoxLayout()
        self.horizontalLayout_delimiter_input.setObjectName("horizontalLayout_delimiter_input")
        self.lineEdit_delimiter_input = QtWidgets.QLineEdit(self.groupBox_delimiter)
        self.lineEdit_delimiter_input.setObjectName("lineEdit_delimiter_input")
        self.horizontalLayout_delimiter_input.addWidget(self.lineEdit_delimiter_input)
        self.pushButton_delimiter_add = QtWidgets.QPushButton(self.groupBox_delimiter)
        self.pushButton_delimiter_add.setObjectName("pushButton_delimiter_add")
        self.horizontalLayout_delimiter_input.addWidget(self.pushButton_delimiter_add)
        self.verticalLayout_delimiter.addLayout(self.horizontalLayout_delimiter_input)
        self.pushButton_delimiter_del = QtWidgets.QPushButton(self.groupBox_delimiter)
        self.pushButton_delimiter_del.setObjectName("pushButton_delimiter_del")
        self.verticalLayout_delimiter.addWidget(self.pushButton_delimiter_del)
        self.gridLayout_3.addWidget(self.groupBox_delimiter, 1, 0, 1, 1)

        self.groupBox_people_config = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_people_config.setObjectName("groupBox_people_config")
        self.groupBox_people_config.setMaximumSize(150, 80)
        self.horizontalLayout_people_config = QtWidgets.QHBoxLayout(self.groupBox_people_config)
        self.horizontalLayout_people_config.setObjectName("horizontalLayout_people_config")
        self.lebel_people_config_thread_number = QtWidgets.QLabel(self.groupBox_people_config)
        self.lebel_people_config_thread_number.setObjectName("lebel_people_config_thread_number")
        self.lebel_people_config_thread_number.setText("线程数:")
        self.horizontalLayout_people_config.addWidget(self.lebel_people_config_thread_number)
        self.lineEdit_people_config_thread_number = QtWidgets.QLineEdit(self.groupBox_people_config)
        self.lineEdit_people_config_thread_number.setObjectName("lineEdit_people_config_thread_number")
        self.lineEdit_people_config_thread_number.setText("10")
        self.horizontalLayout_people_config.addWidget(self.lineEdit_people_config_thread_number)
        self.gridLayout_3.addWidget(self.groupBox_people_config, 1, 1, 1, 1)



        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")

        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_title = QtWidgets.QLabel(self.tab_4)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_7.addWidget(self.label_title)
        self.label_version = QtWidgets.QLabel(self.tab_4)
        self.label_version.setObjectName("label_version")
        self.verticalLayout_7.addWidget(self.label_version)
        self.label_desc = QtWidgets.QLabel(self.tab_4)
        self.label_desc.setObjectName("label_desc")
        self.verticalLayout_7.addWidget(self.label_desc)
        self.label_copyright = QtWidgets.QLabel(self.tab_4)
        self.label_copyright.setObjectName("label_copyright")
        self.verticalLayout_7.addWidget(self.label_copyright)
        self.tabWidget.addTab(self.tab_4, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "代理配置认证"))
        self.label_2.setText(_translate("Form", "代理平台选择"))
        self.label_3.setText(_translate("Form", "用户名"))
        self.label_4.setText(_translate("Form", "密码"))
        self.groupBox_2.setTitle(_translate("Form", "读取邮箱认证"))
        self.label_5.setText(_translate("Form", "用户名"))
        self.label_6.setText(_translate("Form", "密码"))
        self.groupBox_3.setTitle(_translate("Form", "软件认证"))
        self.label.setText(_translate("Form", "秘钥"))
        self.label_7.setText(_translate("Form", "认证状态"))
        self.label_auth_pass_msg.setText(_translate("Form", "xxxx-xx-xx"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "认证"))
        self.groupBox_4.setTitle(_translate("Form", "忽略缓存名单"))
        self.pushButton_link_ignore_add.setText(_translate("Form", "添加"))
        self.pushButton_link_ignore_del.setText(_translate("Form", "删除选中"))
        self.groupBox_5.setTitle(_translate("Form", "特殊页面内容提取规则"))
        self.pushButton_url_pattern_add.setText(_translate("Form", "添加"))
        self.pushButton_url_pattern_del.setText(_translate("Form", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "代理"))
        self.checkBox_data_gen_is_depend.setText(_translate("Form", "工具按钮独立显示"))
        self.checkBox_notification.setText(_translate("Form", "启用弹窗通知"))
        self.checkBox_table_auto_copy.setText(_translate("Form", "启用表格自动复制"))
        self.checkBox_table_copy_line_wrap.setText(_translate("Form", "表格自动换行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "工具"))
        self.groupBox_delimiter.setTitle(_translate("Form", "添加资料分割符"))
        self.pushButton_delimiter_add.setText(_translate("Form", "添加"))
        self.pushButton_delimiter_del.setText(_translate("Form", "删除选中"))
        self.groupBox_people_config.setTitle(_translate("Form", "反查工具配置"))

        item = self.tableWidget_url_pattern.horizontalHeaderItem(0)
        item.setText(_translate("Form", "链接匹配(example.com/re)"))
        item = self.tableWidget_url_pattern.horizontalHeaderItem(1)
        item.setText(_translate("Form", "内容提取规则(re/xpath/bs4/json)"))
        item = self.tableWidget_url_pattern.horizontalHeaderItem(2)
        item.setText(_translate("Form", "提取内容格式化"))

        title_font = QFont("Segoe UI", 20)
        title_font.setBold(True)
        self.label_title.setText("SynthBox 工具箱")
        self.label_title.setFont(title_font)
        self.label_title.setAlignment(Qt.AlignCenter)

        self.label_version.setText("版本 2.0.0")
        self.label_version.setAlignment(Qt.AlignCenter)

        self.label_desc.setText("这是一个集成了多种工具的综合性应用，\n旨在提高您的工作效率。")
        self.label_desc.setAlignment(Qt.AlignCenter)
        self.label_copyright.setText(
            '<a href="https://github.com/your-repo">访问我们的GitHub</a> | © 2025 SynthBox 工具箱'
        )
        self.label_copyright.setOpenExternalLinks(True)
        self.label_copyright.setAlignment(Qt.AlignCenter)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "关于"))
