# TODO 内部链接跳转
# TODO 控件提醒(抖动/窗口/高亮)
# TODO 软件教程
# TODO 增加用户菜单栏(获取卡密弹窗)
# TODO 增加程序代理模式
# TODO 更多代理商ip提取
# TODO 广告过滤
# TODO 自动打码google,微软,cloudflare等验证码
# TODO 文本编辑器/资料导入/自动复制/提取每日日志
# TODO 文本文件格式化(添加空行/分隔符)
# TODO 自动创建/关闭/删除浏览器窗口(添加配置信息/备注等)
# TODO 增加快捷键操作
# TODO 更多小功能(各国驾照生成,id card生成,手机号生成,ip查询等)
# TODO 邮箱域名自定义
# TODO 浏览器自动化脚本制作
# TODO 桌面自动化脚本
# TODO 邮箱一系列操作
# TODO 增加页面提取规则(cookies等)
# TODO 图片生成(证件,小票等)
# TODO 快捷键操作
# TODO 连点器工具
# TODO 键入工具
